<style>
#sideBareMenuGaucheChururgie {
	visibility: hidden
}

#sideBareMenuGaucheChururgie {
	min-width: 200px;
	max-width: 430px;
}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheChururgie').toggle(false);
	$('#sideBareMenuGaucheChururgie').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheChururgie"
	style="color: #cccccc; font-size: 13px; margin-top: 80px; margin-left: 60px;">
	<span> Chargement ... </span>
</div>


<ul id="sideBareMenuGaucheChururgie">
	<!-- MENU ***DOSSIER PATIENT*** -->
	<li id="dossier_patient"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Dossier patient
		</span></a></li>

	<li id="plus_dossier_patient" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."/chururgie/ajouter";?>"> <span
				id="nouveau_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Nouveau</span></a>
		</div>

		<div style="margin-left: 30px; height: 40px;">
			<a href="<?php echo $this->basePath()."/chururgie/liste-patient";?>">
				<img style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>'
				alt='Liste' /> <span id="liste_dossier_patient_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">Liste</span>
			</a>
		</div>
	</li>


	<!-- MENU ***ADMISSION*** -->
	<li id="admission"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Admission
		</span></a></li>

	<li id="plus_admission" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."/chururgie/admission";?>"> <span
				id="admission_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Admettre</span></a>
		</div>

		<div style="margin-left: 30px; height: 40px;">
			<a
				href="<?php echo $this->basePath()."/chururgie/liste-patients-admis";?>">
				<img style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>'
				alt='Liste' /> <span id="liste_admission_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">Liste
					des admis</span>
			</a>
		</div>



	</li>

	
		<!-- MENU ***Liste des Rendez-vous Secretaire*** -->
	<li id="rv-secretaire"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Rendez-vous
		</span></a></li>

	<li id="plus_rv-secretaire" style="background: #4a5765;">
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."/chururgie/liste-rendez-vous";?>"> <span
				id="admission_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> A Confirmer</span></a>
		</div>
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."/chururgie/liste-rendez-vous";?>"> <span
				id="admission_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Liste Rendez-vous </span></a>
		</div>

		



	</li>
	
	
	<!-- MENU ***Consultation *** -->
	<li id="consult_chururgie"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='' /> Consultation Externe
		</span></a></li>

	<li id="plus_consult_chururgie" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."/chururgie/consultation-medecin";?>"> <span
				id="admission_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='' />A Consulter</span></a>
		</div>
			<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="admission_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' />Consultes</span></a>
		</div>
			<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="admission_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' />Recherhcer</span></a>
		</div>

	</li>
	
	
		<!-- MENU ***Hospitalisation*** -->
	<li id="hospitalise"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='' /> Hospitalisation
		</span></a></li>

	<li id="plus_hospitalise" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="hospitaliser_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' />A Hospitaliser</span></a>
		</div>
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="hospitalises_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Hospitalises</span></a>
		</div>
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="rechercher_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Rechercher </span></a>
		</div>

	</li>
	
		<!-- MENU ***Operation*** -->
	<li id="consult_operation"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Operation
		</span></a></li>

	<li id="plus_operation" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="operer_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' />A Operer</span></a>
		</div>
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="operes_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Operer</span></a>
		</div>
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."";?>"> <span
				id="rechercher_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Rechercher </span></a>
		</div>

	</li>
</ul>


<?php
// CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout ()->user;
$role = $user ['role'];


if ($role == 'medecin') {
	?>
<script>
$("#rv-secretaire").toggle(false);
$("#admission").toggle(false);
$("#dossier_patient").toggle(false);
</script>
<?php
}
else if ($role == 'secretaire') {
	?>
<script>
$("#naissance").toggle(false);
$("#deces").toggle(false);
$("#consult_chururgie").toggle(false);
$("#consult_chururgie").toggle(false);
$("#consult_operation").toggle(false);
$("#hospitalise").toggle(false);

</script>
<?php
} else if ($role == 'etat_civil') {
	?>
<script>
$("#consult_operation").toggle(false);
$("#hospitalise").toggle(false);
$("#dossier_patient").toggle(false);
$("#admission").toggle(false);
</script>
<?php
}
?>


<script>
//*******************************************************************************************************************************
//NAISSANCE
function dep1(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Naissances </span></a></li>");
		dep2();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep2(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Naissances </span></a></li>");
		dep1();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_naissance').toggle(false);
$('#naissance').click(function(){
	$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Naissances </span></a></li>");
	dep1();
    $('#plus_naissance').animate({
        height : 'toggle'
    },1000);
 return false;
});

//*******************************************************************************************************************************
//DECES
function dep_deces1(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
		dep_deces2();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_deces2(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
		dep_deces1();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_deces').toggle(false);
$('#deces').click(function(){
	$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
	dep_deces1();
    $('#plus_deces').animate({
        height : 'toggle'
    },1000);
 return false;
});


//*******************************************************************************************************************************
//RENDEZ-VOUS SECRETARIAT
function dep_admission1(){
	$('#rv-secretaire').click(function(){
		$("#admission").replaceWith("<li id='rv-secretaire'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Admission </span></a></li>");
		dep_admission2();
	    $('#plus_rv-secretaire').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission2(){
	$('#rv-secretaire').click(function(){
		$("#rv-secretaire").replaceWith("<li id='rv-secretaire' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
		dep_admission1();
	    $('#plus_rv-secretaire').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_rv-secretaire').toggle(false);
$('#rv-secretaire').click(function(){
	$("#rv-secretaire").replaceWith("<li id='rv-secretaire' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
	dep_admission1();
$('#plus_rv-secretaire').animate({
    height : 'toggle'
},1000);
return false;
});



//ADMISSION
function dep_admission1(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Admission </span></a></li>");
		dep_admission2();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission2(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
		dep_admission1();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admission').toggle(false);
$('#admission').click(function(){
	$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
	dep_admission1();
$('#plus_admission').animate({
    height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//DOSSIER PATIENT
function dep_dossier_patient1(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Dossier Patient </span></a></li>");
		dep_dossier_patient2();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_patient2(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Dossier Patient </span></a></li>");
		dep_dossier_patient1();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_patient').toggle(false);
$('#dossier_patient').click(function(){
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Dossier Patient </span></a></li>");
	dep_dossier_patient1();
$('#plus_dossier_patient').animate({
height : 'toggle'
},1000);
return false;
});



//*******************************************************************************************************************************
//CHURURGIE
function dep_consult_chururgie(){
	$('#consult_chururgie').click(function(){
		$("#consult_chururgie").replaceWith("<li id='consult_chururgie'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> COnsultation Generale </span></a></li>");
		dep_consult_chururgie2
	    $('#plus_consult_chururgie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_consult_chururgie2(){
	$('#consult_chururgie').click(function(){
		$("#consult_chururgie").replaceWith("<li id='consult_chururgie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Consultation Generale </span></a></li>");
		dep_consult_chururgie();
	    $('#plus_consult_chururgie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_consult_chururgie').toggle(false);
$('#consult_chururgie').click(function(){
	$("#consult_chururgie").replaceWith("<li id='consult_chururgie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Consultation Generale </span></a></li>");
	dep_consult_chururgie();
$('#plus_consult_chururgie').animate({
height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************



//*******************************************************************************************************************************
//Hospitalisation
function dep_consult_hospitalisation(){
	$('#hospitalise').click(function(){
		$("#hospitalise").replaceWith("<li id='hospitalise'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_consult_hospitalisation2
	    $('#plus_hospitalise').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_consult_hospitalisation2(){
	$('#hospitalise').click(function(){
		$("#hospitalise").replaceWith("<li id='hospitalise' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_consult_chururgie();
	    $('#plus_hospitalise').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_hospitalise').toggle(false);
$('#hospitalise').click(function(){
	$("#hospitalise").replaceWith("<li id='hospitalise' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Hospitalisation </span></a></li>");
	dep_consult_chururgie();
$('#plus_hospitalise').animate({
height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************


//Operation
function dep_consult_operation(){
	$('#consult_operation').click(function(){
		$("#consult_operation").replaceWith("<li id='consult_operation'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Operation </span></a></li>");
		dep_consult_operation2
	    $('#plus_operation').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_consult_operation2(){
	$('#consult_operation').click(function(){
		$("#consult_operation").replaceWith("<li id='consult_operation' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Operation </span></a></li>");
		dep_consult_operation();
	    $('#plus_operation').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_operation').toggle(false);
$('#consult_operation').click(function(){
	$("#consult_operation").replaceWith("<li id='consult_operation' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Operation </span></a></li>");
	dep_consult_operation();
$('#plus_operation').animate({
height : 'toggle'
},1000);
return false;
});

</script>

