<style>
#sideBareMenuGaucheurgence{ visibility: hidden }

#sideBareMenuGaucheurgence{ min-width:200px; max-width: 430px;}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheurgence').toggle(false);
	$('#sideBareMenuGaucheurgence').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheurgence" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheurgence">
	<!-- MENU ***DOSSIER PATIENT*** -->
	<li id="dossier_patient"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Dossier patient </span></a> </li>

	<li id="plus_dossier_patient" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/urgence/ajout-patient";?>"  >
	       <span id="nouveau_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Nouveau</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/urgence/liste-patient";?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	       <span id="liste_dossier_patient_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste</span></a>
	   </div>
	</li>



	<!-- MENU ***ADMISSION*** -->
	<li id="admission"><a href="">
	   <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Consultation </span></a> 
	</li>

	<li id="plus_admission" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/consultation/liste-patients-admis";?>"  >
	      <span id="liste_admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="margin-top: -7px;" src='<?php echo $this->basePath().'/images_icons/checklist.png'?>' /> Liste des admis</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/consultation/liste-patients-consultes";?>">
	      <img style="margin-left:5px; margin-top: -10px;" src='<?php echo $this->basePath().'/images_icons/tasks.png'?>' />
	      <span id="liste_consultes_style" style="font-size:15px; color: white; font-family:Times New Roman;">Historique</span></a>
	   </div>
	   
	   
	</li>

</ul>


<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

if($role == 'superAdmin'){ ?>
<script>  </script>
<?php } else if($role == 'medecin'){ ?>
<script> $('#dossier_patient').toggle(false); </script>
<?php } ?>


<script>
//*******************************************************************************************************************************
//*******************************************************************************************************************************

//ADMISSION
function dep_admission1(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Consultation </span></a></li>");
		dep_admission2();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission2(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultation </span></a></li>");
		dep_admission1();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admission').toggle(false);
$('#admission').click(function(){
	$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultation </span></a></li>");
	dep_admission1();
$('#plus_admission').animate({
    height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//DOSSIER PATIENT
function dep_dossier_patient1(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_dossier_patient2();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_patient2(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_dossier_patient1();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_patient').toggle(false);
$('#dossier_patient').click(function(){
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
	dep_dossier_patient1();
$('#plus_dossier_patient').animate({
height : 'toggle'
},1000);
return false;
});

</script>

